export const ADMIN_ROUTE = '/admin';
export const ADMIN_ACCOUNT_ROUTE = '/admin';
export const LOGIN_ROUTE = '/login';
export const MAIN_ROUTE = '/';
export const NOTFOUND_ROUTE = '*';
export const API_URL = 'http://localhost:5000/api';
export const SERVER_URL = 'http://localhost:5000/uploads';
export const MAIN_BLOCK_ITEM_ROUTE = '/mainItem';
export const TOUR_BLOCK_ITEM_ROUTE = '/toutItem';
export const PRIVACY_ROUTE = '/privacy-policy';
export const ADMIN_ROUTE_BREADCRUMB = 'админ-панель'
export const LOGIN_ROUTE_BREADCRUMB = 'авторизация'
export const NOTFOUND_ROUTE_BREADCRUMB = '404'
export const PRIVACY_ROUTE_BREADCRUMB = 'политика конфиденциальности'
export const DEV_ROUTE = '/in-developing'
export const DEV_ROUTE_BREADCRUMB = 'в разработке'